### ISSUE TITLE
Wrong request type for saveUserPreferences

### ISSUE THREAD

**Issue by rguthor2** [gnello/php-mattermost-driver#10]
In Client.php it should be PUT instead of POST for saveUserPreferences
`    public function saveUserPreferences(array $requestOptions)
    {
        return $this->client->put(UserModel::$endpoint . '/' . $this->userId . '/preferences', $requestOptions);
    }`

**Comment by gnello** [comment]
Yeah, thank you for pointing it out! I've just fixed it.
