### ISSUE TITLE
tag new version

### ISSUE THREAD

**Issue by brettmc** [gnello/php-mattermost-driver#12]
Hello,
would you be able to tag a new version of the library? (the 4.1 changes are working well for me now that the next release is out...)
thanks!

**Comment by gnello** [comment]
Yes, we're going to upgrade the driver soon

**Comment by gnello** [comment]
Done!

**Comment by brettmc** [comment]
thanks, and my apologies, I didn't see that you had tagged after my changes were merged in (github shows 1.3.0 as "latest" version and all of the 2.x branches are a bit hidden).
