### ISSUE TITLE
Message with File Attached

### ISSUE THREAD

**Issue by emresaracoglu** [gnello/php-mattermost-driver#23]
Hello,

This is great project thank you for your work. 

Can we send post with file?

**Comment by gnello** [comment]
Hi,
sure, have you tried this?

[upload a file](https://api.mattermost.com/#tag/files%2Fpaths%2F~1files%2Fpost) (FileModel -> uploadFile)
[create a post](https://api.mattermost.com/#tag/posts%2Fpaths%2F~1posts%2Fpost) (PostModel -> createPost)

**Comment by emresaracoglu** [comment]
I haven't tried.
I guess it's not possible with your project?

**Comment by gnello** [comment]
Of course it's possible, this client works with all the mattermost endpoints. You simply need to work with the related Model.

[Here](https://github.com/gnello/php-mattermost-driver/tree/master/src/Models) is the list of the models supported.

For example to work with files:
```php
$fileModel = $driver->getFileModel();
```

In your case you have to do something like this to upload a file:
```php
$result = $driver->getFileModel()->uploadFile([
   //..
]);
```
and then use the PostModel to send a post with the file.

Anyway thanks to you I realized that the upload file method is missing 2 parameters, I'll fix it now.

Thanks!

**Comment by gnello** [comment]
Sorry, everythings fine, it should be enough to do:
```php
$result = $driver->getFileModel()->uploadFile([
    'channel_id' => 'The ID of the channel that this file will be uploaded to',
    'filename' => 'The name of the file to be uploaded',
    'files' => 'A file to be uploaded',
]);
```

and then 

```php
$result = $driver->getPostModel()->createPost([
    'channel_id' => 'The channel ID to post in',
    'messages' => 'The message contents, can be formatted with Markdown',
    'file_ids' => 'A list of file IDs to associate with the post',
]);
```

**Comment by emresaracoglu** [comment]
Really, you're great! **Thank you for helping**.
Can you show a sample code in the README.md file? I believe that this will help other people.

**Comment by gnello** [comment]
Sure, I think it's useful, thanks for your suggestion! 
Done :)

**Comment by rkeuter** [comment]
Hi. In the createpost syntax, i had to use 'message' instead of 'messages'. 
Here is my working example:
```

`function upload_and_post_mm ($channel_id,$filename,$files,$messages) {
	include "../includes/mattermost-driver.php";	
	//Upload a file
	$result = $driver->getFileModel()->uploadFile([
		'channel_id' => $channel_id,																			/* 'The ID of the channel that this file will be uploaded to' */
		'filename' => $filename,																				/* 'The name of the file to be uploaded' */
		'files' => fopen($files, 'rb'),																			/* 'Path of the file to be uploaded' */
	]);

	$data 		= (array)json_decode($result->getBody(), true); 												// returns an array
	
	$file_ids	= $data['file_infos'][0]['id'];

	//Send a post with the file just uploaded
	$result = $driver->getPostModel()->createPost([
		'channel_id' => $channel_id,																			/* 'The channel ID to post in' */
		'message' => $messages,																				/* 'The message contents, can be formatted with Markdown' */
		'file_ids' => [$file_ids],																				/* 'A list of file IDs to associate with the post' */
	]);

	//Please read the FileModel class or refer to the api documentation for a complete list of available methods.
}
`
```

**Comment by gnello** [comment]
Hi @rkeuter,
great! Many thanks for pointed that out, I've fixed the README!
