### ISSUE TITLE
Can not upload file 

### ISSUE THREAD

**Issue by tuanvucd** [gnello/php-mattermost-driver#26]
$result = $driver->getFileModel()->uploadFile([
                'channel_id' => $request->channel_id,
                'filename' => $name,
                'files' => $file
]);

I can not upload file when following the readme
.
This is my error

![throw](https://user-images.githubusercontent.com/17537579/62021506-b9907e80-b1f1-11e9-8fd1-c077046a6559.png)

**Comment by gnello** [comment]
Hi,
thanks for pointing out this error, it was very useful for finding a general error on multipart datas that I'll fix soon.
I've just released a fix for your specific case, let me know if it solves.

**Comment by tuanvucd** [comment]
Many thank!. it worked. but can I ask you one more questions?
How can I generate client_ids? The upload File API is required client_ids

**Comment by tuanvucd** [comment]
so I have to change it 

        $option = [
            [
                'name' => 'channel_id',
                'contents' => empty($requestOptions['channel_id']) ? null : $requestOptions['channel_id'],
            ],
            [
                'name' => 'files',
                'filename' => empty($requestOptions['filename']) ? null : $requestOptions['filename'],
                'contents' => empty($requestOptions['files']) ? null : $requestOptions['files'],
            ]
        ];

        if (isset($requestOptions['client_ids'])) {
            $option[] = [
                'name'    => 'client_ids',
                'content' => $requestOptions['client_ids']
            ];
        }

        return $this->client->post(self::$endpoint, $option, RequestOptions::MULTIPART);

(client_ids is not required)

**Comment by gnello** [comment]
Hi,
I'm not sure I understood your question, the `client_ids` param is not required and you can call the `uploadFile` method without passing it

```php
$result = $driver->getFileModel()->uploadFile([
    'channel_id' => '123bcff45',
    'filename' => 'test.jpg',
    'files' => fopen('/path/to/the/file', 'rb'),
]);
```
Is there something wrong with this?

**Comment by tuanvucd** [comment]
Yes, It is not required
![code](https://user-images.githubusercontent.com/17537579/62176060-40686700-b36a-11e9-9881-7a79088f0d0a.png)
But I get an error 
![error](https://user-images.githubusercontent.com/17537579/62176101-6d1c7e80-b36a-11e9-8af1-a89698b44477.png)

**Comment by gnello** [comment]
Oh, you're absolutely right. I'm sorry for this inconvenience.
I've just released the fix, please let me know if you notice anything else.

Thanks.

**Comment by tuanvucd** [comment]
Thank you. It worked perfectly
