### ISSUE TITLE
Methods to manage icons

### ISSUE THREAD

**Issue by pjenicot** [gnello/php-mattermost-driver#29]
Hi,

Could you integrate the following three methods into the "TeamModel" class:
- GET /teams/{team_id}/image
- POST /teams/{team_id}/image
- DELETE /teams/{team_id}/image

thank you
Pierre

**Comment by gnello** [comment]
Hi!
I've just released the 2.11.0 version with a full teams endpoint update.

Sorry for the missed methods :)

**Comment by pjenicot** [comment]
Hi Luca,

I can't use the methods in PHP.

Could you give me an example to send my image to the server using the "`getTeamModel()-> setTeamIcon()`" method?

The server returns a error 400 on each call.

How do we create the `multipart/form-data` request containing the image in `string<binary>` ?

Thanks

**Comment by gnello** [comment]
Sure, 
try this:
```php
$result = $driver->getTeamModel()->setTeamIcon($teamId, [
    'image' => fopen('your_image_path_here', 'rb'),
]);
```

Let me know if it works!

**Comment by pjenicot** [comment]
Thank you ! it's working :)
