### ISSUE TITLE
Returns 500

### ISSUE THREAD

**Issue by JustRostin** [gnello/php-mattermost-driver#30]
When using de mattermost driver it always returns a status code of 500.

The following code is used:
```php
use Gnello\Mattermost\Driver;
 $container = new \Pimple\Container([
            "driver"=>[
                "url"=>"https://mattermost-url.com",
                "login_id"=>"username",
                "password"=>"password",
            ]
        ]);
        $driver = new Driver($container);
        $driver->authenticate();
        $resp = $driver->getPostModel()->createPost([
            'channel_id' => 'channel_id',
            'messages' => 'message'
        ]);
        $status = $resp->getStatusCode();
       return $status;
```
Where status is always 500.

When I use the same credentials using postman it returns 200.

**Comment by gnello** [comment]
Hi,
I can't reproduce this error, could you provide more info about the 500 error?

BTW the parameter to be sent is message (not messages) I just corrected this error in the readme.

**Comment by JustRostin** [comment]
When I get the ReasonPhrase it says `internal server error`, I checked with the system admin that since we already have 2 java accounts like this it is highly likeable that it is caused by the server.

**Comment by JustRostin** [comment]
Hey looked into it with a SR. Dev and found the issue the https:// in the uurl shoudn't be there.

Thanks for looking into it.

**Comment by gnello** [comment]
I'm glad to hear that :)
