### ISSUE TITLE
Laravel 7 support?

### ISSUE THREAD

**Issue by tipjoe** [gnello/php-mattermost-driver#31]
I tried adding **^7.0** to composer.json, but spent two hours trying to get composer to update (with my forked repo) and lost patience. Is this all it needs? 

`    "require": {
        "php": ">=7.0.0",
        "illuminate/support": "^5.0||^6.0||^7.0",
        "gnello/php-mattermost-driver": "^2.3"
    },`

**Comment by gnello** [comment]
Hi,
I've just added laravel 7 support for https://github.com/gnello/laravel-mattermost-driver, it works fine to me. 

I'm not sure about what you're trying to do, are you using the  https://github.com/gnello/laravel-mattermost-driver or the https://github.com/gnello/php-mattermost-driver?

**Comment by gnello** [comment]
Hi,
I’m closing this issue because it has been inactive for a few months. This probably means that it has been fixed by adding Laravel 7 support to https://github.com/gnello/laravel-mattermost-driver.

Please reopen if you still have problems :)

Thank you!
