### ISSUE TITLE
Missing Endpoints in ReactionModel?

### ISSUE THREAD

**Issue by anx-dwuggenig** [gnello/php-mattermost-driver#38]
Hi,

I'm a first time user, the ReactionModel seems a bit empty, I'm not finding this endpoint e.g.: https://api.mattermost.com/#tag/reactions/paths/~1users~1{user_id}~1posts~1{post_id}~1reactions~1{emoji_name}/delete

Am I missing something or was this just forgotten to implement into the model?

**Comment by anx-dwuggenig** [comment]
I've made Pull request here with what I would expect:
https://github.com/gnello/php-mattermost-driver/pull/39

**Comment by gnello** [comment]
Great!
Many thanks for your time!
